---
permalink: api/reference_element_api_createsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,create,creating,snapshot,snapshots,CreateSnapshot 
summary: CreateSnapshot 을 사용하여 볼륨의 특정 시점 복사본을 만들 수 있습니다. 모든 볼륨이나 기존 스냅샷에서 스냅샷을 생성할 수 있습니다. 
---
= 스냅샷 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 사용하여 볼륨의 시점 복사본을 만들 수 `CreateSnapshot` 있습니다. 모든 볼륨이나 기존 스냅샷에서 스냅샷을 생성할 수 있습니다.

이 API 메서드를 사용하여 SnapshotID를 제공하지 않으면 볼륨의 활성 브랜치에서 스냅샷이 생성됩니다. 스냅샷이 생성된 볼륨이 원격 클러스터로 복제되는 경우 스냅샷을 동일한 타겟으로 복제할 수도 있습니다. enableRemoteReplication 매개 변수를 사용하여 스냅샷 복제를 설정합니다.


NOTE: 클러스터 충만도가 1단계, 2단계 또는 3단계에 있는 경우 스냅샷을 생성할 수 있습니다. 클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
`attributes`
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체입니다
 a| 
없음
 a| 
아니요



 a| 
`enableRemoteReplication`
 a| 
스냅샷을 원격 스토리지에 복제할지 여부를 지정합니다. 가능한 값:

* `true`: 스냅샷이 원격 스토리지에 복제됩니다.
* `false`: 스냅샷이 원격 스토리지에 복제되지 않습니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



| `ensureSerialCreation`  a| 
이전 스냅샷 복제가 진행 중인 경우 스냅샷을 생성하지 않도록 지정합니다. 가능한 값은 다음과 같습니다.

* `true`: 이렇게 하면 한 번에 하나의 스냅샷만 복제됩니다. 이전 스냅샷 복제가 아직 진행 중인 경우 새 스냅샷 생성이 실패합니다.
* `false`: 기본값. 다른 스냅샷 복제가 아직 진행 중인 경우 이 스냅샷 생성이 허용됩니다.

| 부울 | `false` | 아니요 


| 만료 시간  a| 
스냅샷을 제거할 수 있는 시간을 지정합니다. 와 함께 사용할 수 `retention` 없습니다. 만료 시간 또는 보존 기간을 지정하지 않으면 스냅샷이 만료되지 않습니다. 시간 형식은 시간 기반 만료에 대한 ISO 8601 날짜 문자열이며, 그렇지 않으면 만료되지 않습니다. 값을 `null` 지정하면 스냅샷이 영구적으로 보존됩니다. 의 값은 `fifo` 볼륨의 다른 FIFO 스냅샷과 비교하여 스냅샷을 선입선출 기준으로 보존합니다. 사용할 수 있는 FIFO 공간이 없으면 API가 실패합니다.
| 문자열 | 없음 | 아니요 


 a| 
`name`
 a| 
스냅샷의 이름입니다. 이름을 입력하지 않으면 스냅샷이 생성된 날짜와 시간이 사용됩니다. 허용되는 최대 이름 길이는 255자입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
`retention`
 a| 
이 매개 변수는 매개 변수와 동일하지만 `expirationTime` 시간 형식이 HH:MM:ss인 경우는 예외입니다.  `expirationTime`또는 을 `retention` 지정하지 않으면 스냅샷이 만료되지 않습니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
`snapMirrorLabel`
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트에 대한 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
`snapshotID`
 a| 
새 스냅샷이 생성된 스냅샷의 고유 ID입니다. 전달된 snapshotID는 지정된 볼륨의 스냅샷이어야 합니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
`volumeID`
 a| 
복사할 볼륨 이미지의 고유 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
체크섬
 a| 
저장된 스냅샷에서 올바른 숫자를 나타내는 문자열입니다. 이 체크섬은 나중에 다른 스냅샷을 비교하여 데이터의 오류를 감지하는 데 사용할 수 있습니다.
 a| 
문자열



 a| 
스냅샷 ID입니다
 a| 
새 스냅샷의 고유 ID입니다.
 a| 
스냅샷 ID입니다



 a| 
스냅샷
 a| 
새로 생성된 스냅샷에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅샷]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "CreateSnapshot",
   "params": {
      "volumeID": 1
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
      "snapshot": {
        "attributes": {},
        "checksum": "0x0",
        "createTime": "2016-04-04T17:14:03Z",
        "enableRemoteReplication": false,
        "expirationReason": "None",
        "expirationTime": null,
        "groupID": 0,
        "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
        "name": "2016-04-04T17:14:03Z",
        "snapshotID": 3110,
        "snapshotUUID": "6f773939-c239-44ca-9415-1567eae79646",
        "status": "done",
        "totalSize": 5000658944,
        "virtualVolumeID": null,
        "volumeID": 1
      },
        "snapshotID": 3110
  }
}
----


== 예외

xNotPrimary 예외는 API가 호출되고 스냅샷을 생성하지 못할 때 `CreateSnapshot` 표시됩니다. 이는 예상된 동작입니다. API 호출을 다시 `CreateSnapshot` 시도하십시오.



== 버전 이후 새로운 기능

9.6
