---
permalink: api/reference_element_api_checkproposednodeadditions.html 
sidebar: sidebar 
keywords: proposed,node,additions,CheckProposedNodeAdditions,storage,checking 
summary: ProposedNodeAdditions 메서드를 사용하여 스토리지 노드 세트를 테스트하여 오류 또는 모범 사례 위반 없이 스토리지 클러스터에 추가할 수 있는지 확인할 수 있습니다. 
---
= ProposedNodeAdveditions를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
메소드를 사용하여 `CheckProposedNodeAdditions` 스토리지 노드 세트를 테스트하여 오류 또는 모범 사례 위반 없이 스토리지 클러스터에 추가할 수 있는지 확인할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
노드
 a| 
스토리지 클러스터에 추가할 준비가 된 스토리지 노드의 스토리지 IP 주소 목록입니다.
 a| 
문자열 배열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
proposedClusterValid
 a| 
제안된 스토리지 노드가 유효한 스토리지 클러스터를 구성할 것인지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
proposedClusterErrors를 참조하십시오
 a| 
제안된 스토리지 노드를 사용하여 스토리지 클러스터를 생성한 경우 발생하는 오류입니다. 가능한 오류 코드:

* `nodesNoCapacity`: 노드에는 가용 용량이 없습니다.
* `nodesTooLarge`: 노드가 활성 보호 구성에 대한 클러스터 용량의 일부를 구성합니다.
* `nodesConnectFailed`: 하드웨어 구성을 쿼리할 노드에 연결할 수 없습니다.
* `nodesQueryFailed`: 하드웨어 구성을 위해 노드를 쿼리할 수 없습니다.
* `nodesClusterMember`: 노드의 IP 주소가 클러스터에서 이미 사용 중입니다.
* `nonFipsNodeCapable`: FIPS 140-2 드라이브 암호화 기능이 활성화되어 있는 동안에는 FIPS를 지원하지 않는 노드를 스토리지 클러스터에 추가할 수 없습니다.
* `nonFipsDrivesCapable`: FIPS 140-2 드라이브 암호화 기능이 활성화되어 있는 동안에는 FIPS를 지원하지 않는 드라이브가 있는 노드를 클러스터에 추가할 수 없습니다.

 a| 
문자열 배열

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
	"method": "CheckProposedNodeAdditions",
	"params": {
	"nodes": [
		"192.168.1.11",
		"192.168.1.12",
		"192.168.1.13",
		"192.168.1.14"
	]
},
	"id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
	"id": 1,
	"result": {
		"proposedClusterValid": true,
		"proposedClusterErrors": [ ]
	}
}
----


== 버전 이후 새로운 기능

11.0
